"""Add new employee fields and create skills and tags tables

Revision ID: 4944dd1195a1
Revises: 
Create Date: 2025-12-10 08:58:54.832926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4944dd1195a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('marital_status', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('passport_number', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('address', sa.JSON(), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact', sa.JSON(), nullable=True))
    op.add_column('employees', sa.Column('job_title_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('probation_end_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('work_shift_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('tag_ids', sa.JSON(), nullable=True))
    op.alter_column('employees', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'employees', 'job_titles', ['job_title_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'work_locations', ['work_location_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'job_positions', ['job_position_id'], ['id'])
    op.drop_column('employees', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.alter_column('employees', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('employees', 'tag_ids')
    op.drop_column('employees', 'work_shift_id')
    op.drop_column('employees', 'probation_end_date')
    op.drop_column('employees', 'job_title_id')
    op.drop_column('employees', 'emergency_contact')
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'passport_number')
    op.drop_column('employees', 'marital_status')
    # ### end Alembic commands ###
